language: objective-c
os: osx
osx_image: xcode 8.3
script:
  - xctool -workspace ZWBarrageDemo/ZWBarrage.xcworkspace -scheme ZWBarrage -sdk iphoneos -configuration Release
  OBJROOT==$PWD/build
  SYMROOT=$PWD/build
  ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
